# -*- coding: utf-8 -*-
$:.unshift("/Library/RubyMotion/lib")
require 'motion/project/template/ios'
require 'joybox'

Motion::Project::App.setup do |app|
  # Use `rake config' to see complete project settings.
  app.name = 'joybox-recipes'
  app.interface_orientations = [:landscape_left]
end
